//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: login.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate `Jeak_LoginClient`, then call methods of this protocol to make API calls.
public protocol Jeak_LoginClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Jeak_LoginClientInterceptorFactoryProtocol? { get }

  func normalLogin(
    _ request: Jeak_NormalLoginRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Jeak_NormalLoginRequest, Jeak_NormalLoginResponse>
}

extension Jeak_LoginClientProtocol {
  public var serviceName: String {
    return "jeak.Login"
  }

  /// Unary call to NormalLogin
  ///
  /// - Parameters:
  ///   - request: Request to send to NormalLogin.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func normalLogin(
    _ request: Jeak_NormalLoginRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Jeak_NormalLoginRequest, Jeak_NormalLoginResponse> {
    return self.makeUnaryCall(
      path: "/jeak.Login/NormalLogin",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeNormalLoginInterceptors() ?? []
    )
  }
}

public protocol Jeak_LoginClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'normalLogin'.
  func makeNormalLoginInterceptors() -> [ClientInterceptor<Jeak_NormalLoginRequest, Jeak_NormalLoginResponse>]
}

public final class Jeak_LoginClient: Jeak_LoginClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Jeak_LoginClientInterceptorFactoryProtocol?

  /// Creates a client for the jeak.Login service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Jeak_LoginClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

