//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: user.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate `Jeak_UserClient`, then call methods of this protocol to make API calls.
public protocol Jeak_UserClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Jeak_UserClientInterceptorFactoryProtocol? { get }

  func getProfile(
    _ request: Jeak_GetProfileRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Jeak_GetProfileRequest, Jeak_GetProfileResponse>
}

extension Jeak_UserClientProtocol {
  public var serviceName: String {
    return "jeak.User"
  }

  /// 获取用户资料
  ///
  /// - Parameters:
  ///   - request: Request to send to GetProfile.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func getProfile(
    _ request: Jeak_GetProfileRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Jeak_GetProfileRequest, Jeak_GetProfileResponse> {
    return self.makeUnaryCall(
      path: "/jeak.User/GetProfile",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetProfileInterceptors() ?? []
    )
  }
}

public protocol Jeak_UserClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'getProfile'.
  func makeGetProfileInterceptors() -> [ClientInterceptor<Jeak_GetProfileRequest, Jeak_GetProfileResponse>]
}

public final class Jeak_UserClient: Jeak_UserClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Jeak_UserClientInterceptorFactoryProtocol?

  /// Creates a client for the jeak.User service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Jeak_UserClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

